<?php
	unlink("jquery.simplyscroll.css");
	unlink("sequencejs-theme.sliding-horizontal-parallax.css");
	unlink("style.css");
	unlink("../about.html");
	unlink("../contact.php");
	unlink("../contacto.php");
	unlink("../cotizacion.php");
	unlink("../index.html");
	unlink("../inicio.html");
	unlink("../manufactura.html");
	unlink("../manufacturing.html");
	unlink("../nosotros.html");
	unlink("../productos.php");
	unlink("../products.php");
	unlink("../quotation.php");
?>